### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

### ISSUE THREAD

**Issue by almereyda** [KmolYuan/kmol-editor#4]
After installing with

    pip3 install --user -r requirements.txt

and running with

    python3 launch_kmol.py

the console outputs

```
Traceback (most recent call last):
  File "launch_kmol.py", line 8, in <module>
    from core import main
  File "/home/yala/src/github.com/KmolYuan/kmol-editor/core/__init__.py", line 12, in <module>
    from .main_window import MainWindow
  File "/home/yala/src/github.com/KmolYuan/kmol-editor/core/main_window/__init__.py", line 27, in <module>
    from core.QtModules import (
  File "/home/yala/src/github.com/KmolYuan/kmol-editor/core/QtModules.py", line 20, in <module>
    from PyQt5.QtWebEngineWidgets import *
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

Testing for it to exist:

```
# pip3 install --user pyqtwebengine
Requirement already satisfied: pyqtwebengine in /home/yala/.local/lib/python3.7/site-packages (5.12.1)
Requirement already satisfied: PyQt5>=5.12 in /usr/local/lib64/python3.7/site-packages (from pyqtwebengine) (5.12.1)
Requirement already satisfied: PyQt5_sip<4.20,>=4.19.14 in /usr/local/lib64/python3.7/site-packages (from PyQt5>=5.12->pyqtwebengine) (4.19.15)
```

reveals that it is actually there.

**Comment by KmolYuan** [comment]
Well, `pyqtwebengine` is the requirement of latest PyQt5 if used any web browser widget. Make sure the version of them are the same (recommend stable version `5.12`). If it does, the location of distribution package may be caused the error, because of your PyQt is not install in user directory, unless to recompile them manually. Test to import it if installed correctly:

```bash
python3 -c "import PyQt5.QtWebEngineWidgets"
```

If it didn't, install the package without `--user` option:

```bash
sudo pip3 install pyqtwebengine
```

or through the package manager of OS, like `apt` in Debian and Ubuntu:

```bash
sudo apt install python3-pyqt5.qtwebengine
```
